image: node:latest

stages:
  - build

build:
  stage: build
  when: manual
  script:
    - echo _auth=$NPM_PUBLSH_KEY >> .npmrc
    - npm ci
    - npm publish
    - echo "-- build completed succesfully"
  only:
    - main