image: node:latest

stages:
  - build

build:
  stage: build
  when: manual
  script:
    - npm i
    - echo _auth=$NPM_PUBLSH_KEY >> .npmrc
    - echo email=<youremail> >> .npmrc
    - echo always-auth=true >> .npmrc
    - cat .npmrc
    - npm publish
  only:
    - main